version: '3'
services:
  template-flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: template-flask
    volumes:
      - ./logs:/app/logs:rw
      - ./database:/app/database:rw
    ports:
    - "5000:5000"
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: template.gnps2.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: template.gnps2.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com
      ADMIN_PW: ${ADMIN_PW}
      SECRET_KEY: ${SECRET_KEY}



networks:
  nginx-net:
    external:
      name: nginx-net